spring:
  application:
    name: collector-api-gateway
  cloud:
    gateway:
      routes:
        - id: static-data-route
          uri: http://${STATIC_DATA_HOST:static-data-service}:${STATIC_DATA_PORT:8081}
          predicates:
            - Path=/api/v1/static/**
        - id: dynamic-data-route
          uri: http://${DYNAMIC_DATA_HOST:dynamic-data-service}:${DYNAMIC_DATA_PORT:8082}
          predicates:
            - Path=/api/v1/dynamic/**
        - id: admin-route
          uri: http://${ADMIN_HOST:admin-service}:${ADMIN_PORT:8083}
          predicates:
            - Path=/api/v1/admin/**
server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    io.batterypass: DEBUG
    org.springframework.cloud.gateway: INFO